apiVersion: v1
kind: Namespace
metadata:
  name: walkai
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-client
  namespace: walkai
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-to-api-client
  namespace: walkai
subjects:
  - kind: ServiceAccount
    name: api-client
    namespace: walkai
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: discovery-minimal
rules:
  - nonResourceURLs: ["/api", "/api/*", "/apis", "/apis/*", "/version"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: discovery-minimal-for-walkai-api-client
subjects:
  - kind: ServiceAccount
    name: api-client
    namespace: walkai
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: discovery-minimal
---
apiVersion: v1
kind: Secret
metadata:
  name: api-client-permanent-token
  namespace: walkai
  annotations:
    kubernetes.io/service-account.name: api-client
type: kubernetes.io/service-account-token
